version: "3.8"

services:
  # -------------------------------------------------------------------
  #                         CENTRAL POSTGRES
  # -------------------------------------------------------------------
  central-postgres:
    image: postgres:15
    container_name: central_postgres_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
      - central_postgres_data:/var/lib/postgresql/data
    networks:
      - intelligence-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  # -------------------------------------------------------------------
  #                           API GATEWAY
  # -------------------------------------------------------------------
  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "3000:3000"
    networks:
      - intelligence-network
    depends_on:
      central-postgres:
        condition: service_healthy
    environment:
      - DB_HOST=central-postgres
      - DB_PORT=5432
      - DB_NAME=user_data_db
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
      - CHOKIDAR_USEPOLLING=true
      - JWT_SECRET=mysecret
      - PORT=3000
    volumes:
      - ./api-gateway:/server
      - node_modules1:/server/node_modules
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always

  # -------------------------------------------------------------------
  #                      USER MANAGEMENT SERVICE
  # -------------------------------------------------------------------
  user-management-service:
    build:
      context: ./user-management
    ports:
      - "4000:4000"
    networks:
      - intelligence-network
    depends_on:
      central-postgres:
        condition: service_healthy
    environment:
      - DB_HOST=central-postgres
      - DB_PORT=5432
      - DB_NAME=user_data_db
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
      - CHOKIDAR_USEPOLLING=true
      - PORT=4000
      - JWT_SECRET=mysecret
    volumes:
      - ./user-management:/server
      - node_modules2:/server/node_modules
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always

  # -------------------------------------------------------------------
  #                       COMMUNITY SERVICE
  # -------------------------------------------------------------------
  community-service:
    build:
      context: ./community-service
    ports:
      - "4001:4001"
    networks:
      - intelligence-network
    depends_on:
      central-postgres:
        condition: service_healthy
    environment:
      - DB_HOST=central-postgres
      - DB_PORT=5432
      - DB_NAME=community_db
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
      - CHOKIDAR_USEPOLLING=true
      - PORT=4001
    volumes:
      - ./community-service:/server
      - node_modules3:/server/node_modules
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4001"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always

  # -------------------------------------------------------------------
  #                      COURSE GENERATION SERVICE
  # -------------------------------------------------------------------
  # course-generation:
  #   build:
  #     context: ./course-generation
  #   ports:
  #     - "4002:5000"
  #   networks:
  #     - intelligence-network
  #   depends_on:
  #     central-postgres:
  #       condition: service_healthy
  #   environment:
  #     - DB_HOST=central-postgres
  #     - DB_PORT=5432
  #     - DB_NAME=course_db
  #     - DB_USER=myuser
  #     - DB_PASSWORD=mypassword
  #     - CHOKIDAR_USEPOLLING=true
  #     - PORT=5000
  #   volumes:
  #     - ./course-generation:/server
  #     - node_modules4:/server/node_modules
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:5000"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3
  #   restart: always

networks:
  intelligence-network:
    driver: bridge

volumes:
  central_postgres_data:
  node_modules1:
  node_modules2:
  node_modules3:
  node_modules4:
#main