version: "3.8"

services:
  # -------------------- API GATEWAY --------------------
  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "3000:3000"
    networks:
      - intelligence-network
    environment:
      - DB_HOST=user-data-db
      - DB_PORT=5432
      - DB_NAME=user-data-db
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
      - CHOKIDAR_USEPOLLING=true
      - JWT_SECRET=mysecret
      - PORT=3000
    volumes:
      - ./api-gateway:/server
      - node_modules1:/server/node_modules
    restart: unless-stopped

  # -------------------- USER MANAGEMENT --------------------
  user-management-service:
    build:
      context: ./user-management
    ports:
      - "4000:4000"
    depends_on:
      - user-data-db
    networks:
      - intelligence-network
    environment:
      - DB_HOST=user-data-db
      - DB_PORT=5432
      - DB_NAME=user-data-db
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
      - CHOKIDAR_USEPOLLING=true
      - PORT=4000
      - JWT_SECRET=mysecret
    volumes:
      - ./user-management:/server
      - node_modules2:/server/node_modules
    restart: unless-stopped

  # -------------------- USER DATA DB --------------------
  user-data-db:
    image: postgres:15
    container_name: postgres_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: user-data-db
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    networks:
      - intelligence-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  # -------------------- COMMUNITY SERVICE --------------------
  community-service:
    build:
      context: ./community-service
    ports:
      - "4001:4001"
    depends_on:
      - community-db
    networks:
      - intelligence-network
    environment:
      - DB_HOST=community-db
      - DB_PORT=5433
      - DB_NAME=community-db
      - DB_USER=communityuser
      - DB_PASSWORD=communitypassword
      - CHOKIDAR_USEPOLLING=true
      - PORT=4001
    volumes:
      - ./community-service:/server
      - node_modules3:/server/node_modules
    restart: unless-stopped

  # -------------------- COMMUNITY DB --------------------
  community-db:
    image: postgres:15
    container_name: community_postgres_container
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: community-db
      POSTGRES_USER: communityuser
      POSTGRES_PASSWORD: communitypassword
    networks:
      - intelligence-network
    volumes:
      - community_postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

networks:
  intelligence-network:
    driver: bridge

volumes:
  postgres_data:
  community_postgres_data:
  node_modules1:
  node_modules2:
  node_modules3:
